version: '3.9'

services:
  bot:
    build: .
    container_name: my_bot
    command: python main.py
    env_file: .env
    volumes:
      - .:/app
      - ./tickets:/app/tickets
    networks:
      - my_network

  api:
    build: .
    container_name: my_api
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - my_network

  ticket:
    build: .
    container_name: check
    command: python check_reg.py
    env_file: .env
    volumes:
      - .:/app
    networks:
      - my_network



networks:
  my_network:
